In [1]:
import pyscf
from pyscf import tools, symm
import numpy as np

scf_energy=[]
atoms = []
r0 = 0.8 
basis = "6-31G"
#basis="sto3g"
molecule = """
    C   0.63 0.63 0.63
    H   1.26 1.26 0.0
    H   0.0 1.26 1.26
    H   1.26 0.0 1.26
    H   -0.6  -0.6 -0.6
    """
print(molecule)
basis = basis
mol = pyscf.gto.Mole(
    atom    =   molecule,
    symmetry=True,
    spin    =   0,
    charge  =   0,
    basis   =   basis)
mol.build()
mf = pyscf.scf.ROHF(mol)
mf.verbose = 4
mf.conv_tol = 1e-8
mf.conv_tol_grad = 1e-5
mf.chkfile = "scf.fchk"
mf.init_guess = "sad"
mf.run(max_cycle=200)









    C   0.63 0.63 0.63
    H   1.26 1.26 0.0
    H   0.0 1.26 1.26
    H   1.26 0.0 1.26
    H   -0.6  -0.6 -0.6
    


******** <class 'pyscf.scf.hf_symm.SymAdaptedROHF'> ********
method = SymAdaptedROHF-ROHF-RHF
initial guess = sad
damping factor = 0
level_shift factor = 0
DIIS = <class 'pyscf.scf.diis.CDIIS'>
diis_start_cycle = 1
diis_space = 8
SCF conv_tol = 1e-08
SCF conv_tol_grad = 1e-05
SCF max_cycles = 200
direct_scf = True
direct_scf_tol = 1e-13
chkfile to save SCF result = scf.fchk
max_memory 4000 MB (current use 119 MB)
num. doubly occ = 5  num. singly occ = 0
init E= -39.6469438182461
HOMO (A') = -0.262571582218092  LUMO (A') = -0.0514648205255
cycle= 1 E= -39.9924445962879  delta_E= -0.346  |g|= 0.162  |ddm|= 1.05
HOMO (A') = -0.368829804050241  LUMO (A') = 0.0478337398963281
cycle= 2 E= -40.0031791225067  delta_E= -0.0107  |g|= 0.0559  |ddm|= 0.119
HOMO (A') = -0.357996435285858  LUMO (A') = 0.0652476233673926
cycle= 3 E= -40.004486834657  delta_E= -0.00131  |g|= 0.0318 

SymAdaptedROHF-ROHF-RHF object of <class 'pyscf.scf.hf_symm.SymAdaptedROHF'>

In [2]:
norb = mf.mo_coeff.shape[0]
    #print(mf.mo_coeff)
print(norb)
pyscf.tools.molden.from_mo(mol, "C_RHF_CH4.molden", mf.mo_coeff)
for s,i,c in zip(mol.irrep_name, mol.irrep_id, mol.symm_orb):
    print(" %5s %3i %4i"%(s, i, c.shape[1]))

def myocc(mf):    
    mol = mf.mol
    irrep_id = mol.irrep_id
    so = mol.symm_orb
    orbsym = symm.label_orb_symm(mol, irrep_id, so, mf.mo_coeff)
    occsym = np.array(orbsym)[mf.mo_occ==2]
    virsym = np.array(orbsym)[mf.mo_occ==0]
    for ir,irname in enumerate(mol.irrep_name):
        print('%5s, Occ = %5d, Vir = %d' % (irname, sum(occsym==ir), sum(virsym==ir)))
        print(orbsym)
        print(mol.irrep_id)
        print(mol.irrep_name)
myocc(mf)

17
    A'   0   13
    A"   1    4
   A', Occ =     4, Vir = 9
[0 0 0 1 0 0 0 0 1 0 1 0 0 0 0 1 0]
[0, 1]
["A'", 'A"']
   A", Occ =     1, Vir = 3
[0 0 0 1 0 0 0 0 1 0 1 0 0 0 0 1 0]
[0, 1]
["A'", 'A"']


In [3]:
pyscf.scf.hf_symm.analyze(mf)

**** SCF Summaries ****
Total Energy =                         -40.004846851600334
Nuclear Repulsion Energy =              11.698831440310951
One-electron Energy =                  -75.909716459917348
Two-electron Energy =                   24.206038168006060
Wave-function symmetry = A'
occupancy for each irrep:     A'   A"
                               4    1
**** MO energy ****
MO #1 (A' #1), energy= -11.2976580467287 occ= 2
MO #2 (A' #2), energy= -0.939786015456253 occ= 2
MO #3 (A' #3), energy= -0.576792190575381 occ= 2
MO #4 (A" #1), energy= -0.576792190575381 occ= 2
MO #5 (A' #4), energy= -0.357791257276895 occ= 2
MO #6 (A' #5), energy= 0.0657322998961312 occ= 0
MO #7 (A' #6), energy= 0.251989125189437 occ= 0
MO #8 (A' #7), energy= 0.310290670038869 occ= 0
MO #9 (A" #2), energy= 0.310290670038872 occ= 0
MO #10 (A' #8), energy= 0.726683380526863 occ= 0
MO #11 (A" #3), energy= 0.726683380526862 occ= 0
MO #12 (A' #9), energy= 0.836538273497643 occ= 0
MO #13 (A' #10), energy= 1.06118

((array([1.99998524, 1.11529214, 0.00481948, 1.04619097, 1.04619097,
         1.04619097, 0.00738833, 0.00738833, 0.00738833, 0.86211009,
         0.00900589, 0.86211009, 0.00900589, 0.86211009, 0.00900589,
         1.08944956, 0.01636772]),
  array([-0.28083477,  0.12888402,  0.12888402,  0.12888402, -0.10581728])),
 array([0.98834471, 0.98834471, 0.98834471]))